export const ApiEndpoints = {
  BaseURL: 'http://django:8080/',
  BaseApi: '/api',
  login: '/auth/login/',
  register: '/auth/register/',
  Token: '/auth/refresh/',
  proyectos: '/proyectos/',
  lotes: '/lotes/',
  areas: '/areas/',
  Plantas: '/plantas/',
  Poligonos: '/geolotes/',
  perfil: '/auth/porfile/',
  Lectura: '/lecturas/',
  Enfermedad: '/enfermedades/',
};
